/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.util.LinkedList;
import model.Client;
import model.Fish;
import model.img;

/**
 *
 * @author toshiba
 */
public class Jframe extends javax.swing.JFrame {

    private img Background;

    public Jframe() {
        this.setUndecorated(true);
        initComponents();
        this.Background = new img(0, 0, 1366, 768, "../img/bg.jpg");
        this.draw.Receive(Background);
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        draw = new view.Draw();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        draw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drawMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout drawLayout = new javax.swing.GroupLayout(draw);
        draw.setLayout(drawLayout);
        drawLayout.setHorizontalGroup(
            drawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        drawLayout.setVerticalGroup(
            drawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(draw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(draw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawMouseClicked
    }//GEN-LAST:event_drawMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Jframe frame=new Jframe(); 
                GraphicsDevice gd=
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                
                if (gd.isFullScreenSupported()) {
                    frame.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                    frame.setResizable(false);
                    gd.setFullScreenWindow(frame);
                    System.out.println(frame.getWidth()+"x"+frame.getHeight());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.Draw draw;
    // End of variables declaration//GEN-END:variables


    /**
     * @return the draw
     */
    public view.Draw getDraw() {
        return draw;
    }

    /**
     * @param draw the draw to set
     */
    public void setDraw(view.Draw draw) {
        this.draw = draw;
    }
}